# Copyright (c) <year> <author> (<email>)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "vNAGaVAB7eCZ+3BOVhAZ2IZxqRKI0XqvpIyn8YIF6Fn/bANXyqoB//OPY+CcVsI1eCkexa8ePDIXAVGADZqHEqcZ07prkc1SyQtJfECAjR8wiirk+XfYODaebfyHYnBhcF00Q6+bB8lq2rpPyk2LCtzts30Wd94dE8fIrKm22czKgnKmfnH+tLg5VFlGaff6uTVIrXgtNfE8PDp199ACiEWu1EDQm68lLAD1ekPucAIp0PZYptMBWT2pD5T+cHVyCtt4kOjl7ESqalIxdI9+F9h8UBaLNUctXhGXPHALcC3SVMSzhv7Xsg/vuhf8g3zX9JzYWO/hVzr2/urPdZKSZHAVRGxOB73ORyNwm/PozRYk30nqqn9mFaELgwUXtdRSaXLTEMSdWGmWmDlVyVjo6PMP2Ua8qox40Hgaaa/Cxud38/3zVsYLnlfx+EkzPWfDJU5BTlVnmk2tGX9M3DKoRd1u8rYNhVWb7q8c87TN2WcbIN9ASaHpXvoBjPR+WuMoMiOjwpniVyJdAcn0YB0jf0yFam5DoZfLHoWHisg4W3zYJy08HszqyMZ3GlPRDq9YTqhU8j52MFRb7zYhOXJCVFeAcBj6skv0GzWtkqO2/j7xzq9Kgelzir6vZQfYi6A6IJ9FluWoG9UO4Av+/AECKcHdXoplJqOa7J1X9VwoB9U="
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH_PATTERN=coverity_scan
    - compiler: gcc
      env: COVERITY_SCAN_BRANCH_PATTERN=coverity_scan BUILD_TYPE=Release

addons:
  coverity_scan:
    project:
      name: "kartikkumar/cppbase"
      description: "Build submitted via Travis CI"
    notification_email: me@kartikkumar.com
    build_command_prepend: "mkdir build; cd build; cmake -DPROJECT_NAME=cppbase -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on .."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - bash scripts/install_cmake.sh
  - bash scripts/install_doxygen.sh
  - chmod ugo+x scripts/check_doxygen.sh
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ] && [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ]; then
      echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
      pip install --user cpp-coveralls;
    fi

script:
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ]; then
      mkdir build;
      cd build;
      $HOME/cmake/bin/cmake -DPROJECT_NAME=cppbase -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DDOXYGEN_EXECUTABLE=$HOME/doxygen/bin/doxygen -DBUILD_DOXYGEN_DOCS=on ..;
      make;
      ctest -V;
      ../scripts/check_doxygen.sh;
    fi

after_success:
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ] && [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ]; then
      coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*src/main.cpp.*";
    fi
